package com.example.kaafkaproject

 object ListMenu {
 val menuItems = listOf(
    MenuItem("BAKSO LAVA",30000, R.drawable.bakso_lava),
    MenuItem("BAKSO URAT",18000, R.drawable.bakso_urat),
    MenuItem("BAKSO TELUR",20000, R.drawable.bakso_telur),
    MenuItem("BAKSO POLOS",17000, R.drawable.bakso_polos),
    MenuItem("MIE YAMIN",17000, R.drawable.yamin_pangsit_bakso),
    MenuItem("MIE YAMIN BAKSO",20000, R.drawable.yamin_pangsit_bakso),
    MenuItem("MIE YAMIN PANGSIT",20000, R.drawable.yamin_pangsit_bakso),
    MenuItem("BIHUN YAMIN",17000, R.drawable.bihun),
    MenuItem("BIHUN YAMIN BAKSO",20000, R.drawable.bihun),
    MenuItem("BIHUN YAMIN PANGSIT",20000, R.drawable.bihun),
    MenuItem("PANGSIT KUAH",17000, R.drawable.pangsit1),
    MenuItem("PANGSIT GORENG",17000, R.drawable.pangsit_goreng),
    MenuItem("KWETIAW KUAH",17000, R.drawable.kwetiauw),
    MenuItem("KWETIAW GORENG",18000, R.drawable.kwetiauw),
    MenuItem("KWETIAW BAKSO",20000, R.drawable.kwetiauw),
    MenuItem("KWETIAW PANGSIT",20000, R.drawable.kwetiauw),
    MenuItem("MIE TEKTEK",18000, R.drawable.tektek),
    MenuItem("DIMSUM",15000, R.drawable.dimsum),
    MenuItem("SIOMAY",15000, R.drawable.siomay),
    MenuItem("DIMSUM SAOS MENTAI",20000, R.drawable.dimsum_mentai),
    MenuItem("NASI CHICKEN KATSU",20000, R.drawable.nasi_katsu),
    MenuItem("NASI AYAM PENYET",20000, R.drawable.nasi_penyet),
    MenuItem("NASI SUP IKAN",20000, R.drawable.nasi_sup_ikan),
    MenuItem("NASI AYAM RICA RICA",25000, R.drawable.nasi_rica),
    MenuItem("SEBLAK CEKER",20000, R.drawable.seblak),
    MenuItem("TEH TAWAR PANAS",3000, R.drawable.teh_hangat),
    MenuItem("TEH TAWAR DINGIN",3000, R.drawable.es_teh),
    MenuItem("TEH MANIS PANAS",5000, R.drawable.teh_hangat),
    MenuItem("TEH MANIS DINGIN",5000, R.drawable.es_teh),
    MenuItem("AIR MINERAL",5000, R.drawable.mineral),
    MenuItem("TEH BOTOL",5000, R.drawable.teh_botol),
    MenuItem("LEMON TEA PANAS",10000, R.drawable.lemon_hangat),
    MenuItem("LEMON TEA DINGIN",10000, R.drawable.es_lemon),
    MenuItem("JERUK PERAS PANAS",8000, R.drawable.jeruk_peras_hangat),
    MenuItem("JERUK PERAS DINGIN",8000, R.drawable.es_jeruk_peras),
    MenuItem("ES CINGCAU SELASIH",12000, R.drawable.cincau_selasih),
    MenuItem("ES CAPPUCINO",10000, R.drawable.es_capucinno),
    MenuItem("ES COKLAT",15000, R.drawable.es_coklat),
    MenuItem("ES TEH TARIK",10000, R.drawable.teh_tarik),
    MenuItem("KOPI HITAM",5000, R.drawable.kopi),
    MenuItem("KENTANG GORENG",10000, R.drawable.kentang),
    MenuItem("Pangsit",2000, R.drawable.pangsit1),
    MenuItem("Bakso Kecil",2000, R.drawable.bakso1),
    MenuItem("Kerupuk",3000, R.drawable.kerupuk),
    MenuItem("Es Batu",1000, R.drawable.es_batu),
    MenuItem("Indomie",4000, R.drawable.indomie),
    MenuItem("Sambal",4000, R.drawable.sambal),
    MenuItem("Bakso Lava ",20000, R.drawable.lava1),
    MenuItem("Bakso Telur",12000, R.drawable.bakso_telur1),
    MenuItem("Bakso Urat",10000, R.drawable.urat1),
    MenuItem("Sup Ikan",15000, R.drawable.sup_ikan1),
    MenuItem("Ayam (Katsu/Rica2)",15000, R.drawable.katsu1),
    MenuItem("Nasi Putih",5000, R.drawable.nasi_putih)

)
}